import { StyleSheet } from 'react-native'
import { ThemeColors } from '@/constants/Colors'

export const createStyles = (colors: ThemeColors) => StyleSheet.create({
  outerContainer: {
    flex: 1,
  },
  profileTabBar: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  profileTab: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 12,
  },
  profileTabActive: {
    borderBottomWidth: 2,
    borderBottomColor: colors.borderActive,
  },
  profileTabText: {
    color: colors.textFaint,
    fontSize: 15,
    fontWeight: '500',
  },
  profileTabTextActive: {
    color: colors.text,
    fontWeight: '600',
  },
  container: {
    flex: 1,
    padding: 24,
    gap: 24,
  },
  profileHeader: {
    alignItems: 'center',
    gap: 8,
    paddingVertical: 8,
  },
  avatarWrapper: {
    position: 'relative' as const,
    marginBottom: 4,
  },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.backgroundButtonStrong,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarImage: {
    width: 80,
    height: 80,
    borderRadius: 40,
  },
  avatarBadge: {
    position: 'absolute' as const,
    bottom: 0,
    right: 0,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.text,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: colors.background,
  },
  avatarText: {
    color: colors.text,
    fontSize: 26,
    fontWeight: '700',
  },
  profileName: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '600',
  },
  profileEmail: {
    color: colors.textMuted,
    fontSize: 14,
  },
  section: {
    gap: 8,
  },
  sectionTitle: {
    color: colors.textFaint,
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  toggleRow: {
    flexDirection: 'row',
    gap: 0,
    borderRadius: 12,
    overflow: 'hidden',
  },
  toggleOption: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    backgroundColor: colors.backgroundCard,
  },
  toggleOptionActive: {
    backgroundColor: colors.text,
  },
  toggleText: {
    color: colors.textFaint,
    fontSize: 14,
    fontWeight: '600',
  },
  toggleTextActive: {
    color: colors.background,
  },
  searchInput: {
    backgroundColor: colors.backgroundInput,
    borderRadius: 10,
    padding: 12,
    color: colors.text,
    fontSize: 15,
  },
  searchResultsList: {
    backgroundColor: colors.backgroundCard,
    borderRadius: 12,
    padding: 8,
    gap: 4,
  },
  friendsList: {
    gap: 4,
  },
  friendRow: {
    flexDirection: 'row' as const,
    alignItems: 'center',
    gap: 10,
    paddingVertical: 8,
    paddingHorizontal: 8,
    backgroundColor: colors.backgroundCard,
    borderRadius: 10,
  },
  friendAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
  },
  friendAvatarFallback: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.backgroundButtonStrong,
    alignItems: 'center',
    justifyContent: 'center',
  },
  friendAvatarText: {
    color: colors.textFaint,
    fontSize: 12,
    fontWeight: '700',
  },
  friendName: {
    flex: 1,
    color: colors.text,
    fontSize: 14,
    fontWeight: '500',
  },
  friendAddButton: {
    flexDirection: 'row' as const,
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.text,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  friendAddButtonText: {
    color: colors.background,
    fontSize: 12,
    fontWeight: '600',
  },
  friendRemoveButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: colors.errorBackground,
  },
  friendsEmptyText: {
    color: colors.textMuted,
    fontSize: 13,
    textAlign: 'center' as const,
    paddingVertical: 8,
  },
  adminCard: {
    backgroundColor: colors.backgroundCard,
    borderRadius: 12,
    padding: 12,
    gap: 8,
  },
  adminHeaderRow: {
    flexDirection: 'row' as const,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.textFaint + '33',
  },
  adminRow: {
    flexDirection: 'row' as const,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: colors.textFaint + '15',
  },
  adminCell: {
    flex: 1,
    fontSize: 12,
    color: colors.text,
  },
  adminHeaderCell: {
    flex: 1,
    fontSize: 11,
    fontWeight: '700' as const,
    color: colors.textFaint,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.3,
  },
  adminStatusText: {
    color: colors.textFaint,
    fontSize: 13,
    textAlign: 'center' as const,
    paddingVertical: 12,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: colors.errorBackground,
    marginTop: 8,
  },
  logoutText: {
    color: colors.error,
    fontSize: 16,
    fontWeight: '600',
  },
})
