import { StyleSheet } from 'react-native'
import { ThemeColors } from '@/constants/Colors'

export const createStyles = (colors: ThemeColors) => StyleSheet.create({
  outerContainer: {
    flex: 1,
  },
  profileTabBar: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  profileTab: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 12,
  },
  profileTabActive: {
    borderBottomWidth: 2,
    borderBottomColor: colors.borderActive,
  },
  profileTabText: {
    color: colors.textFaint,
    fontSize: 15,
    fontWeight: '500',
  },
  profileTabTextActive: {
    color: colors.text,
    fontWeight: '600',
  },
  container: {
    flex: 1,
    padding: 24,
    gap: 24,
  },
  profileHeader: {
    alignItems: 'center',
    gap: 10,
    paddingVertical: 8,
  },
  avatarWrapper: {
    position: 'relative' as const,
    alignItems: 'center',
    marginBottom: 4,
  },
  avatar: {
    width: 92,
    height: 92,
    borderRadius: 46,
    backgroundColor: colors.backgroundButtonStrong,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarImage: {
    width: 92,
    height: 92,
    borderRadius: 46,
  },
  avatarEditBadge: {
    position: 'absolute' as const,
    right: -2,
    bottom: -2,
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.text,
    borderWidth: 2,
    borderColor: colors.background,
  },
  avatarText: {
    color: colors.text,
    fontSize: 30,
    fontWeight: '700',
  },
  profileName: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '600',
    marginTop: 6,
  },
  profileEmail: {
    color: colors.textMuted,
    fontSize: 14,
  },
  section: {
    gap: 10,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: colors.textFaint,
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  sectionAction: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: colors.text,
    alignItems: 'center',
    justifyContent: 'center',
  },
  preferencesCard: {
    backgroundColor: colors.backgroundCard,
    borderRadius: 12,
    padding: 12,
  },
  preferenceLabel: {
    color: colors.textMuted,
    fontSize: 13,
    fontWeight: '500',
  },
  preferenceDivider: {
    height: 1,
    backgroundColor: colors.border,
    marginVertical: 10,
  },
  languageRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
  },
  languageRowValue: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  languageRowValueText: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '500',
  },
  themeSection: {
    gap: 10,
  },
  themeTileRow: {
    flexDirection: 'row',
    gap: 10,
  },
  themeTile: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 16,
    borderRadius: 12,
    backgroundColor: colors.backgroundInput,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  themeTileActive: {
    backgroundColor: colors.text,
    borderColor: colors.text,
  },
  themeTileText: {
    color: colors.textMuted,
    fontSize: 13,
    fontWeight: '600',
  },
  themeTileTextActive: {
    color: colors.background,
  },
  pickerOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: colors.overlay,
  },
  pickerSheet: {
    backgroundColor: colors.backgroundElevated,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 16,
    paddingHorizontal: 20,
    paddingBottom: 28,
  },
  pickerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  pickerTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '700',
  },
  pickerClose: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.backgroundButton,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  pickerRowText: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '500',
  },
  pickerRowTextActive: {
    fontWeight: '700',
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 32,
    paddingHorizontal: 16,
    gap: 8,
    backgroundColor: colors.backgroundCard,
    borderRadius: 12,
  },
  emptyStateText: {
    color: colors.textMuted,
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center' as const,
  },
  emptyStateHint: {
    color: colors.textFaint,
    fontSize: 12,
    textAlign: 'center' as const,
  },
  friendsList: {
    gap: 6,
  },
  friendRow: {
    flexDirection: 'row' as const,
    alignItems: 'center',
    gap: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
    backgroundColor: colors.backgroundCard,
    borderRadius: 10,
  },
  friendAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  friendAvatarFallback: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.backgroundButtonStrong,
    alignItems: 'center',
    justifyContent: 'center',
  },
  friendAvatarText: {
    color: colors.textFaint,
    fontSize: 13,
    fontWeight: '700',
  },
  friendName: {
    flex: 1,
    color: colors.text,
    fontSize: 14,
    fontWeight: '500',
  },
  friendRemoveButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: colors.errorBackground,
  },
  requestsCountBadge: {
    minWidth: 20,
    height: 20,
    paddingHorizontal: 6,
    borderRadius: 10,
    backgroundColor: colors.error,
    alignItems: 'center',
    justifyContent: 'center',
  },
  requestsCountBadgeText: {
    color: colors.background,
    fontSize: 11,
    fontWeight: '700',
  },
  requestAcceptButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: colors.text,
  },
  requestDeclineButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: colors.errorBackground,
  },
  requestButtonDisabled: {
    opacity: 0.5,
  },
  adminCard: {
    backgroundColor: colors.backgroundCard,
    borderRadius: 12,
    padding: 12,
    gap: 8,
  },
  adminHeaderRow: {
    flexDirection: 'row' as const,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.textFaint + '33',
  },
  adminRow: {
    flexDirection: 'row' as const,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: colors.textFaint + '15',
  },
  adminCell: {
    flex: 1,
    fontSize: 12,
    color: colors.text,
  },
  adminHeaderCell: {
    flex: 1,
    fontSize: 11,
    fontWeight: '700' as const,
    color: colors.textFaint,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.3,
  },
  adminStatusText: {
    color: colors.textFaint,
    fontSize: 13,
    textAlign: 'center' as const,
    paddingVertical: 12,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: colors.errorBackground,
  },
  logoutText: {
    color: colors.error,
    fontSize: 16,
    fontWeight: '600',
  },
})
